name: Prod Branch Deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
    #   - ".github/workflows/**"
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use SSH Action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hng_boilerplate_python_fastapi_web
            git add .
            git stash
            git checkout main
            git pull origin main
            source venv-prod/bin/activate
            pip install -r requirements.txt
            alembic upgrade head
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart python-bp-prod.service


